# Generated by Django 4.1.2 on 2022-10-08 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Concurso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.IntegerField(unique=True, verbose_name="Concurso")),
                ("data", models.DateField(verbose_name="Data do sorteio")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Cadastrado em"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Modificado em"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Grupo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Nome do Grupo"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Cadastrado em"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Modificado em"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Jogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numeros",
                    models.CharField(
                        help_text="Exemplo 1, 2, 3, 4",
                        max_length=100,
                        verbose_name="Jogos",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Cadastrado em"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Modificado em"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Resultado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resultado",
                    models.CharField(
                        help_text="Exemplo 1, 2, 3, 4",
                        max_length=150,
                        verbose_name="Resultado",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Cadastrado em"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Modificado em"
                    ),
                ),
                (
                    "concurso_resultado",
                    models.ForeignKey(
                        help_text="Concuros dos jogos",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.concurso",
                        verbose_name="Concurso",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JogosGrupo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Cadastrado em"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Modificado em"
                    ),
                ),
                (
                    "concurrso_jogos",
                    models.ForeignKey(
                        help_text="concurso dos Jogos",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.concurso",
                        verbose_name="Concurso",
                    ),
                ),
                (
                    "grupo",
                    models.ForeignKey(
                        help_text="concurso dos Jogos",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.grupo",
                        verbose_name="Grupo",
                    ),
                ),
            ],
        ),
    ]
