# Generated by Django 4.1.2 on 2022-10-08 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jogosgrupo",
            name="membros",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="membros_grupo",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Membros",
            ),
        ),
        migrations.AddField(
            model_name="jogo",
            name="concurso",
            field=models.ForeignKey(
                help_text="Concurso dos jogos",
                on_delete=django.db.models.deletion.CASCADE,
                to="core.concurso",
                verbose_name="Concurso",
            ),
        ),
        migrations.AddField(
            model_name="jogo",
            name="grupo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.jogosgrupo"
            ),
        ),
    ]
